name: Deploy container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up QEMU #(for support many platforms)
      uses: docker/setup-qemu-action@v1
      
    - name: Build Jar
      run: make    
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push container
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: arm64
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_IMAGE_TAG }}
          
# Тоже работает
#     - name: Build Docker container
#       run: |
#           docker build --platform=linux/arm64 -t ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKER_IMAGE }} -o type=registry .
          
    - name: Stop container via ssh command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_ADDRESS }}
        username: ${{ secrets.HOST_USER }}
        port: ${{ secrets.HOST_PORT }}
        key: ${{ secrets.HOST_KEY }}
        script: |
         (docker stop ${{ secrets.DOCKER_IMAGE }} 2>/dev/null || true)
         (docker rm ${{ secrets.DOCKER_IMAGE }} 2>/dev/null || true) 

    - name: Start container via ssh command 
      uses: cross-the-world/ssh-pipeline@master

      with:
        host: ${{ secrets.HOST_ADDRESS }}
        user: ${{ secrets.HOST_USER }}
        key: ${{ secrets.HOST_KEY }}
        port: ${{ secrets.HOST_PORT }}
        connect_timeout: 10s
        script: |
          docker pull ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_IMAGE_TAG }}
          docker run ${{ secrets.DOCKER_RUNPARAMS }} ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_IMAGE_TAG }}
